AppData\Local\nvim:
  type: git-repo
  url: "https://github.com/Hier0nim/nvim.git"
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

.glzr:
  type: git-repo
  url: "https://github.com/Hier0nim/.glzr.git"
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

.config/wezterm/:
  type: git-repo
  url: "https://github.com/Hier0nim/wezterm-config.git"
  exact: true
  stripComponents: 1
  refreshPeriod: 168h
